src/docker.py
src/utils.py

Sets status to Blocked and write the reason Message in juju status. E.g. for docker upgrades:

Improved feedback when upgrade fails

---

RELEASE.md

Sourced from https://github.com/dwellir-public/ops/blob/release-docs/juju/RELEASE.md after discussion with me, @erik78se and @jonathanudd 
Outlines the first version of our release strategy for the polkadot-operator charm.

Add release strategy documentation

---

src/service_args.py

This should let us deploy Tinkernet nodes with `--chain=tinkernet`, easy.
One issue: they include `tinker-raw.json` in every release - this way of downloading it uses a hard-coded URL. I'm guessing the `tinker-raw.json` in their releases will likely be the same as on the main branch, which is the URL I added here, but can we be sure?
Opinion? @jonathanudd

Add InvArch Tinkernet chainspec download

---

README.md
config.yaml
src/utils.py

- Makes the charm able to install multiple binaries, since that's now required (https://github.com/paritytech/polkadot-sdk/releases/tag/polkadot-v1.1.0). Does this by accepting a list of URL:s to the `binary-url` config, see examples in the code.
- Also updates `sha256` check to work with a list as well. New behavior will be that if no `binary-sha256-url` is supplied, no check will be made, e.g. we change from opt-in rather than opt-out as the default setting.
Note: a DEB package is also included in the latest Polkadot release, but me and @jonathanudd decided that handling those is a separate thing to pursue. Better to get support for multiple binaries merged quickly, and then look at what we want to do with DEB.
Thoughts?
Would be nice to merge a solution for the new Polkadot release …

Polkadot 1.1.0 adaptions - multiple binary support

---

.github/workflows/release.yml

`v5` listed as the latest tag here: https://github.com/canonical/data-platform-workflows/tags

Update Canonical GitHub workflows version to v5

---

.github/workflows/release.yml

Reason: may solve issue in [Revision 11 release job](https://github.com/dwellir-public/polkadot-operator/actions/runs/6415769424)

Downgrade workflow to v4 due to error in release job

---

.vscode/settings.json
README.md
actions.yaml
config.yaml
requirements.txt
src/charm.py
src/docker.py
src/utils.py

Charm updates to be included in Revision 14.
- [Updated binary-sha256-url description](https://github.com/dwellir-public/polkadot-operator/pull/31/commits/17e41d408803d251551a13c705eb824eb1c3fb35)
- [Add actions to stop and to start the polkadot service](https://github.com/dwellir-public/polkadot-operator/pull/31/commits/63001b2f7cb27ff21c9077689d92230a73ccd626)
- [Some readme updates and restructuring](https://github.com/dwellir-public/polkadot-operator/pull/31/commits/4db285d3e06065f04dbbd117da70d011ba192e0b)
- [Upgrade ops version to 2.9](https://github.com/dwellir-public/polkadot-operator/pull/31/commits/b7c43a9a85776d3efc2c7893cb84632a37b48503)
- [v2.8](https://github.com/canonical/operator/releases/tag/2.8.0) comes with a `Unit.reboot()` implementation and …

Revision 14

---

actions.yaml
charmcraft.yaml
config.yaml
src/charm.py
src/polkadot_rpc_wrapper.py

Using substrate-interface Python library to make more advanced RPC calls. Today it is quite difficult and annoying to find out which node is validating. One typically go to `polkadot.js` to find out which session key a validator is using. And then check if that session key exist on any of our nodes. With these actions it can be done directly on the node instead. I also improved the `Validating` status message to actually show if the node is currently validating or will be next era. So basically it would be enough to just run `juju status` to know if the node is validating.
No rush with this PR. I would also need to test it on a real validator first to test all the functionality.

Using substrate-interface lib for session key actions.

---

README.md
metadata.yaml
src/charm.py
src/interface_rpc_url_provider.py
src/interface_rpc_url_requirer.py
src/service_args.py

Became a bit harder for several reasons:
1. Found out that multiple relay nodes can be configured which will then work automatically as fallback. Example: `--relay-chain-rpc-urls ws://10.207.153.56:9933 ws://10.207.153.189:9933`
And of course the interface should support that.
2. Seems to be a bug in Juju where the relation data is not available in the departed hook. A problem since using multiple relay nodes we need to know which one to remove. I have reported this in the Matrix chat. I made a work around storing some extra info in `_stored_`.

Added interface for connecting parachain nodes to relaychain nodes.

---

src/docker.py
src/service_args.py

Adds Polkadex mainnet as custom option for `--chain`, includes both Docker client install and Docker spec file install.
The spec file part might not be necessary at length, due to https://github.com/dwellir-public/polkadot-operator/pull/36, but since I have to add the Docker specialization I'm throwing it in there for now anyway.
Deploying nodes with a local build of this commit.

Add Polkadex mainnet as custom chain name for Docker and spec file

---

src/charm.py

So the error I posted here https://github.com/dwellir-public/polkadot-operator/pull/51#issuecomment-1991784772 was due to this typo. Keys in event result can't have underscore.

Fixed typo in event result key for action

---

actions.yaml

Adapted to Juju 3, but leaving the old description in place for some time.

Fix description of get-node-help action

---

src/charm.py
src/constants.py
src/utils.py

I often get stuck at this when upgrading or deploying:
`self.unit.status = ops.WaitingStatus("Service running, client starting up")`
and then I usually run `jhack ffwd` to get the "real" status.
It's quite common that it can take up to 1 min after an upgrade.

Increase the number of attemps for status

---

src/utils.py

`download_file(...)` was hard-coded to run `chown` for `c.WASM_PATH`, when it should be for the `filepath` which was just downloaded and written to. Also did minor cleanup for this code.
Edit: [confirmed working with live charm.](https://dwellersofaisir.slack.com/archives/C04AK9F7N6N/p1712129561317549?thread_ts=1712073660.020019&cid=C04AK9F7N6N)

Fix download_file()

---

src/charm.py
src/utils.py

With this, we'll get a version check with each of the `update_status_simple` calls as per [the idea from the previous PR](https://github.com/dwellir-public/polkadot-operator/pull/55#issuecomment-2028897449).

Add client binary version get for update_status_simple

---

src/constants.py
src/docker.py
src/service_args.py
src/tarball.py
src/utils.py

Constants in the constants.py should be named after what they represent e.g. `_DIR` for directories and `_FILE` for files.

Clean up constants based on file/dir

---

src/charm.py

I got tired of always having to remove the dot from the address when double-click-copying it.

Remove the ending dot when printing validator address.

---

src/charm.py

Sometimes (e.g. enjin) one needs to enter the session keys separately. I have manually split it every time. This saves some time.
Example result from the action:
```
session-key-0: 0xef6109abc7fce16e585cc2e1feb2a005324d3ddec89a1a3e5f42b39c84563827
session-key-1: 0xbac5d1409d3fff746003b7226573d2877356325bff70aea8322a69d7f04e6f69
session-key-2: 0xfe8877a235e06d818d8381f3e2d2c0e915d3e65cbc9cc23f261c6d189bdc1c16
session-key-3: 0xfa41478f2c31d3421a22ab8270a8449b943ba7df996f3cfb56d7061a8d652a0a
session-key-4: 0x2a774692c397178238492ca32f985325cc8965b89cbd6d15ded1bd1c035ef801
session-keys-merged: 0xef6109abc7fce16e585cc2e1feb2a005324d3ddec89a1a3e5f42b39c84563827bac5d1409d3fff746003b7226573d2877356325bff70aea8322a69d7f04e6f69fe8877a235e06d818d8381f3e2d2c0e915d3e65cbc9cc23f261c6d189bdc1c16fa41478f2 …
```

print the session key splitted for convenience

---

src/docker.py

They changed the directory structure. But we are using the spec url config parameters instead so should I just remove it or update to the new path?

[kilt] Not copying chainspecs from docker image

---

src/docker.py

The initial `chain_name` variable `hyperbridge-nexus` was with the assumption that it will be deployed with its spec file in the `chain-spec-url` config. It can be deployed with `nexus` without using  a spec file.

fix hyperbridge deployment

---

.github/workflows/release.yml
charmcraft.yaml

* Update data-platform-workflows to v26.0.0 (#92)
* tmp: only run build job and for this branch. REMOVE BEFORE MAIN
* Using the new platforms keyword for charmcraft 3.3.0
* bumped data-platform-workflows to 26.0.1 and set charmcraft version to 3.3.0
* setting channel instead of revision for charmcraft
* Using short hand notation for platforms to be compatible with data-platform-workflows
* Trying setting revision again for charmcraft
* using revision number instead of version number
* Added the release job again and set main branch
---------

Fix build workflow (#93)

---

src/charm.py
src/utils.py

Config change on binary url or docker tag or snap would auto start the workload if it is in a stopped state.
This MR would cause the workload to restart only if it is already in a running state otherwise the only binary or snap would be updated and the start would have to be triggered via the run command.

Fix: Config change should not auto start the workload
